# Generated by Django 2.2.3 on 2019-07-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Produto', models.CharField(max_length=30)),
                ('Categoria', models.CharField(max_length=30)),
                ('Número_de_série', models.IntegerField()),
                ('Quantidade', models.IntegerField()),
                ('Preço', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Descrição', models.TextField()),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='produto_fotos')),
                ('Data', models.DateField()),
            ],
        ),
    ]
